### ISSUE TITLE
Issues with Functional Load Calculations

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#486]
1. It seems to be possible to calculate the minimal pair functional load using either type or token frequency. That is not what we say in the documentation -- we claim that it's only possible with Delta-H. How is token frequency being included in the minimal pair calculation? We should update the documentation.

2. When a list of pairs is provided for the command line implementation, there is no option to treat them as separate pairs instead of all together (or at least, the resulting output file gives a single "result" functional load rather than separate results for each pair). This should be parameterized the way it was originally in the GUI (before we added the option to make pairs based on features). 

3. In the command line, there also doesn't seem to be an option to return the raw number of minimal pairs (it's returning only the count relative to the number of possible pairs). Again, this should be parameterized.

4. The way that the environment selection is working is off -- for example, when trying to calculate the FL of B and D word initially before AA in the IPHOD corpus (#__AA), many of the words are accurate (e.g., it finds bogs/dogs, box/docks, etc.), but it also seems to be including ANY words that are minimal pairs hinging on B and D that happen to have either a #BAA or #DAA sequence (e.g., barb/bard, Bobby/body). This should be fixed.

**Comment by bhallen** [comment]
1. Things have gotten a little convoluted since type/token frequency is now specified in context managers, rather than as an argument to the FL functions, but it does seem now that token frequency can be used with minpair_fl. Based on going over the code, I think that it gives the (bizarre) outcome that for each minimal pair, the "number of minimal pairs" for it is the average of the pair's token frequencies. It's difficult for me to check right now because of my OS issues, but is something like this what you actually find? If so, I imagine we want to change this, right?

2. This should be possible now. Please try using the flag -x and let me know how it goes.

3. The way to specify this is by adding '-r False'. If you think that it makes more sense to have raw (non-relative) minimal pair count be the default, I can make this instead into just a flag '-r' that would be necessary to get relative counts.

4. Good find---that's definitely a bug. I'll work on it ASAP.

**Comment by kchall** [comment]
1. Yeah, that seems very odd. I can think about whether a token frequency option even makes sense here, but it might be sensible just to remove that option again.

2. Great! I think it's basically working. The output file is a little bit weirdly formatted, though. It would be useful for the first entry to list the original segment pair. I think this might be intended based on the column names, but currently, what I actually get is the list of minimal pairs under "result", the actual functional load score under "segment(s)", and no actual listing of which segments were used.

3. Great; this seems to work for me. I think it's fine to have the relative frequencies be the default. But we should add information about this argument to the documentation. 

4. Thanks!
4. Thanks!

**Comment by bhallen** [comment]
4. This bug should be fixed for minpair functional load now. I'll need to take a slightly different approach to fix it for deltah, but I'll do that too ASAP.

1. I can't seem to replicate the format you describe. Could you please send me your output file and the script call that generated it?

**Comment by kchall** [comment]
2. Here's the result file with the weird formatting. This was created with the following command:
pct_funcload iphod.corpus -p diff_pairs.txt -x -a minpair -t type -q \# -w AA -o initial_before_AA_mp.txt

[initial_before_AA_mp.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/36065/initial_before_AA_mp.txt)

(Also, don't lose track of the original bug in (4)!) :)

**Comment by bhallen** [comment]
Note to self: take out token frequency option for minpair_fl.

(And also fix Item 2 above.)

**Comment by kchall** [comment]
Item 4: Hmm, I think this is still not working for me. I synced to the master and then ran 

sudo python3 setup.py install 

...from the synced directory to make sure it was the one installed. But when I run: 

pct_funcload iphod.corpus -p diff_pairs.txt -x -a minpair -t type -q \# -w AA -o initial_before_AA_mp.txt

...I still get "body" / "Bobbie" and "Bard" / "Barb" as minimal pairs that are being included (incorrectly).

**Comment by bhallen** [comment]
I didn't mean to actually close this issue yet, but with the last commit, I think I fixed the "Item 4 bug". It took a complete revision of how the minpair_fl function works, but I think the new version is cleaner and clearer anyway. Plus, it should lack the bug: I created my own bobby/body/bot/dot corpus and tested it on both the CL and GUI (although, of course, with no context manager in the GUI).

Note to self: I still need to 1) take out token frequency option from minpair_fl, 2) fix the format of the output file, and 3) add the '-r False" option to the docs

**Comment by kchall** [comment]
Item 4 looks good to me!

**Comment by bhallen** [comment]
I've fixed the output file format for "separate pairs" minpair FL. Thanks for pointing out that there was a bug in the previous format. I hope that this one works better! Once we refactor our analysis functions to return dictionaries, we can go back and make any more changes to the output that we want.

...and with that, I think that this multi-part issue can finally be closed!
